/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ghost;
import processing.core.*;
import java.awt.Robot;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    // Checking an App being initialised is not null
    @Test 
    public void nullTest() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest);
    }

    // Testing screen drawing in normal case
    @Test
    public void setUpTest_1(){
        App app = new App();
        PApplet.runSketch(new String[]{""}, app);
        app.noLoop();
    }

    // Testing screen drawing in frightened mode
    @Test
    public void setUpTest_2(){
        App app =  new App();
        app.frightened = true;
        PApplet.runSketch(new String[]{""}, app);
        app.noLoop();
    }

    // Testing screen drawing in debug mode
    @Test
    public void setUpTest_3(){
        App app =  new App();
        app.debug = true;
        PApplet.runSketch(new String[]{""}, app);
        app.noLoop();
    }

    // Testing screen drawing in soda mode
    @Test
    public void setUpTest_4(){
        App app = new App();
        app.soda = true;
        PApplet.runSketch(new String[]{""}, app);
        app.noLoop();
    }
}
